//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Employee
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnUserNameChanged()
        {
            this.___OnPropertyChanged("UserName");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnCurrentChanged()
        {
            this.___OnPropertyChanged("Current");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Employee.DetailsClass.IImplementation.RiskAssessor
        {
            get
            {
                return this.RiskAssessor;
            }
            set
            {
                this.RiskAssessor = (global::LightSwitchApplication.Implementation.RiskAssessor)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessor> __RiskAssessor
        {
            get
            {
                if (this.___RiskAssessor == null)
                {
                    this.___RiskAssessor = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessor>(
                        this,
                        "RiskAssessor",
                        new string[] { "Id" },
                        e => global::System.Object.Equals(e.Id, this.Id),
                        () => this._RiskAssessor,
                        e => this._RiskAssessor = e);
                }
                return this.___RiskAssessor;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessor> ___RiskAssessor;
        
    }
    #endregion
    
    #region HazardType
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class HazardType :
        global::LightSwitchApplication.HazardType.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnHazardTypeDescriptionChanged()
        {
            this.___OnPropertyChanged("HazardTypeDescription");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.HazardType.DetailsClass.IImplementation.RiskAssessmentHazards
        {
            get
            {
                return this.RiskAssessmentHazards;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessmentHazard> __RiskAssessmentHazards
        {
            get
            {
                if (this.___RiskAssessmentHazards == null)
                {
                    this.___RiskAssessmentHazards = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessmentHazard>(
                        this,
                        "RiskAssessmentHazards",
                        () => this._RiskAssessmentHazards,
                        e => global::System.Object.Equals(e.HazardType_RiskAssessmentHazard, this.Id));
                }
                return this.___RiskAssessmentHazards;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessmentHazard> ___RiskAssessmentHazards;
        
    }
    #endregion
    
    #region RiskAssessmentHazard
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class RiskAssessmentHazard :
        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.IImplementation
    {
        partial void OnHazardType_RiskAssessmentHazardChanged()
        {
            this.___OnPropertyChanged("HazardType_RiskAssessmentHazard");
            this.___OnPropertyChanged("HazardType");
        }
        
        partial void OnRiskAssessmentHazard_RiskAssessmentChanged()
        {
            this.___OnPropertyChanged("RiskAssessmentHazard_RiskAssessment");
            this.___OnPropertyChanged("RiskAssessment");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnHazardDescriptionChanged()
        {
            this.___OnPropertyChanged("HazardDescription");
        }
        
        partial void OnHazardConsequenceChanged()
        {
            this.___OnPropertyChanged("HazardConsequence");
        }
        
        partial void OnControlMeasuresChanged()
        {
            this.___OnPropertyChanged("ControlMeasures");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.IImplementation.HazardType
        {
            get
            {
                return this.HazardType;
            }
            set
            {
                this.HazardType = (global::LightSwitchApplication.Implementation.HazardType)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.HazardType> __HazardType
        {
            get
            {
                if (this.___HazardType == null)
                {
                    this.___HazardType = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.HazardType>(
                        this,
                        "HazardType",
                        new string[] { "HazardType_RiskAssessmentHazard" },
                        e => global::System.Object.Equals(e.Id, this.HazardType_RiskAssessmentHazard),
                        () => this._HazardType,
                        e => this._HazardType = e);
                }
                return this.___HazardType;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.HazardType> ___HazardType;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.IImplementation.RiskAssessment
        {
            get
            {
                return this.RiskAssessment;
            }
            set
            {
                this.RiskAssessment = (global::LightSwitchApplication.Implementation.RiskAssessment)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessment> __RiskAssessment
        {
            get
            {
                if (this.___RiskAssessment == null)
                {
                    this.___RiskAssessment = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessment>(
                        this,
                        "RiskAssessment",
                        new string[] { "RiskAssessmentHazard_RiskAssessment" },
                        e => global::System.Object.Equals(e.Id, this.RiskAssessmentHazard_RiskAssessment),
                        () => this._RiskAssessment,
                        e => this._RiskAssessment = e);
                }
                return this.___RiskAssessment;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessment> ___RiskAssessment;
        
    }
    #endregion
    
    #region RiskAssessmentReview
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class RiskAssessmentReview :
        global::LightSwitchApplication.RiskAssessmentReview.DetailsClass.IImplementation
    {
        partial void OnRiskAssessmentReview_RiskAssessorChanged()
        {
            this.___OnPropertyChanged("RiskAssessmentReview_RiskAssessor");
            this.___OnPropertyChanged("RiskAssessmentReviewer");
        }
        
        partial void OnRiskAssessmentReview_RiskAssessmentChanged()
        {
            this.___OnPropertyChanged("RiskAssessmentReview_RiskAssessment");
            this.___OnPropertyChanged("RiskAssessment");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnDateDueChanged()
        {
            this.___OnPropertyChanged("DateDue");
        }
        
        partial void OnDateCompletedChanged()
        {
            this.___OnPropertyChanged("DateCompleted");
        }
        
        partial void OnOutcomeChanged()
        {
            this.___OnPropertyChanged("Outcome");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RiskAssessmentReview.DetailsClass.IImplementation.RiskAssessmentReviewer
        {
            get
            {
                return this.RiskAssessmentReviewer;
            }
            set
            {
                this.RiskAssessmentReviewer = (global::LightSwitchApplication.Implementation.RiskAssessor)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessor> __RiskAssessmentReviewer
        {
            get
            {
                if (this.___RiskAssessmentReviewer == null)
                {
                    this.___RiskAssessmentReviewer = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessor>(
                        this,
                        "RiskAssessmentReviewer",
                        new string[] { "RiskAssessmentReview_RiskAssessor" },
                        e => global::System.Object.Equals(e.Id, this.RiskAssessmentReview_RiskAssessor),
                        () => this._RiskAssessmentReviewer,
                        e => this._RiskAssessmentReviewer = e);
                }
                return this.___RiskAssessmentReviewer;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessor> ___RiskAssessmentReviewer;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RiskAssessmentReview.DetailsClass.IImplementation.RiskAssessment
        {
            get
            {
                return this.RiskAssessment;
            }
            set
            {
                this.RiskAssessment = (global::LightSwitchApplication.Implementation.RiskAssessment)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessment> __RiskAssessment
        {
            get
            {
                if (this.___RiskAssessment == null)
                {
                    this.___RiskAssessment = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessment>(
                        this,
                        "RiskAssessment",
                        new string[] { "RiskAssessmentReview_RiskAssessment" },
                        e => global::System.Object.Equals(e.Id, this.RiskAssessmentReview_RiskAssessment),
                        () => this._RiskAssessment,
                        e => this._RiskAssessment = e);
                }
                return this.___RiskAssessment;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessment> ___RiskAssessment;
        
    }
    #endregion
    
    #region RiskAssessment
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class RiskAssessment :
        global::LightSwitchApplication.RiskAssessment.DetailsClass.IImplementation
    {
        partial void OnRiskType_RiskAssessmentChanged()
        {
            this.___OnPropertyChanged("RiskType_RiskAssessment");
            this.___OnPropertyChanged("RiskType");
        }
        
        partial void OnRiskAssessment_RiskAssessorChanged()
        {
            this.___OnPropertyChanged("RiskAssessment_RiskAssessor");
            this.___OnPropertyChanged("RiskAssessor");
        }
        
        partial void OnRiskAssessmentStatus_RiskAssessmentChanged()
        {
            this.___OnPropertyChanged("RiskAssessmentStatus_RiskAssessment");
            this.___OnPropertyChanged("RiskAssessmentStatus");
        }
        
        partial void OnRiskAssessment_RiskAssessor1Changed()
        {
            this.___OnPropertyChanged("RiskAssessment_RiskAssessor1");
            this.___OnPropertyChanged("RiskAssessmentApprover");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnReferenceNumberChanged()
        {
            this.___OnPropertyChanged("ReferenceNumber");
        }
        
        partial void OnRiskAssessmentTitleChanged()
        {
            this.___OnPropertyChanged("RiskAssessmentTitle");
        }
        
        partial void OnProcessDescriptionChanged()
        {
            this.___OnPropertyChanged("ProcessDescription");
        }
        
        partial void OnPersonsAffectedChanged()
        {
            this.___OnPropertyChanged("PersonsAffected");
        }
        
        partial void OnHowPersonsAffectedChanged()
        {
            this.___OnPropertyChanged("HowPersonsAffected");
        }
        
        partial void OnInherentLikelihoodChanged()
        {
            this.___OnPropertyChanged("InherentLikelihood");
        }
        
        partial void OnInherentImpactChanged()
        {
            this.___OnPropertyChanged("InherentImpact");
        }
        
        partial void OnInherentRiskChanged()
        {
            this.___OnPropertyChanged("InherentRisk");
        }
        
        partial void OnControlMeasuresChanged()
        {
            this.___OnPropertyChanged("ControlMeasures");
        }
        
        partial void OnControlledLikehoodChanged()
        {
            this.___OnPropertyChanged("ControlledLikehood");
        }
        
        partial void OnControlledImpactChanged()
        {
            this.___OnPropertyChanged("ControlledImpact");
        }
        
        partial void OnControlledRiskChanged()
        {
            this.___OnPropertyChanged("ControlledRisk");
        }
        
        partial void OnDateApprovedChanged()
        {
            this.___OnPropertyChanged("DateApproved");
        }
        
        partial void OnDateEffectiveChanged()
        {
            this.___OnPropertyChanged("DateEffective");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RiskAssessment.DetailsClass.IImplementation.RiskType
        {
            get
            {
                return this.RiskType;
            }
            set
            {
                this.RiskType = (global::LightSwitchApplication.Implementation.RiskType)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskType> __RiskType
        {
            get
            {
                if (this.___RiskType == null)
                {
                    this.___RiskType = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskType>(
                        this,
                        "RiskType",
                        new string[] { "RiskType_RiskAssessment" },
                        e => global::System.Object.Equals(e.Id, this.RiskType_RiskAssessment),
                        () => this._RiskType,
                        e => this._RiskType = e);
                }
                return this.___RiskType;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskType> ___RiskType;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RiskAssessment.DetailsClass.IImplementation.RiskAssessor
        {
            get
            {
                return this.RiskAssessor;
            }
            set
            {
                this.RiskAssessor = (global::LightSwitchApplication.Implementation.RiskAssessor)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessor> __RiskAssessor
        {
            get
            {
                if (this.___RiskAssessor == null)
                {
                    this.___RiskAssessor = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessor>(
                        this,
                        "RiskAssessor",
                        new string[] { "RiskAssessment_RiskAssessor" },
                        e => global::System.Object.Equals(e.Id, this.RiskAssessment_RiskAssessor),
                        () => this._RiskAssessor,
                        e => this._RiskAssessor = e);
                }
                return this.___RiskAssessor;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessor> ___RiskAssessor;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RiskAssessment.DetailsClass.IImplementation.RiskAssessmentStatus
        {
            get
            {
                return this.RiskAssessmentStatus;
            }
            set
            {
                this.RiskAssessmentStatus = (global::LightSwitchApplication.Implementation.RiskAssessmentStatus)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessmentStatus> __RiskAssessmentStatus
        {
            get
            {
                if (this.___RiskAssessmentStatus == null)
                {
                    this.___RiskAssessmentStatus = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessmentStatus>(
                        this,
                        "RiskAssessmentStatus",
                        new string[] { "RiskAssessmentStatus_RiskAssessment" },
                        e => global::System.Object.Equals(e.Id, this.RiskAssessmentStatus_RiskAssessment),
                        () => this._RiskAssessmentStatus,
                        e => this._RiskAssessmentStatus = e);
                }
                return this.___RiskAssessmentStatus;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessmentStatus> ___RiskAssessmentStatus;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RiskAssessment.DetailsClass.IImplementation.RiskAssessmentApprover
        {
            get
            {
                return this.RiskAssessmentApprover;
            }
            set
            {
                this.RiskAssessmentApprover = (global::LightSwitchApplication.Implementation.RiskAssessor)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessor> __RiskAssessmentApprover
        {
            get
            {
                if (this.___RiskAssessmentApprover == null)
                {
                    this.___RiskAssessmentApprover = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessor>(
                        this,
                        "RiskAssessmentApprover",
                        new string[] { "RiskAssessment_RiskAssessor1" },
                        e => global::System.Object.Equals(e.Id, this.RiskAssessment_RiskAssessor1),
                        () => this._RiskAssessmentApprover,
                        e => this._RiskAssessmentApprover = e);
                }
                return this.___RiskAssessmentApprover;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RiskAssessor> ___RiskAssessmentApprover;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.RiskAssessment.DetailsClass.IImplementation.RiskAssessmentReviews
        {
            get
            {
                return this.RiskAssessmentReviews;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessmentReview> __RiskAssessmentReviews
        {
            get
            {
                if (this.___RiskAssessmentReviews == null)
                {
                    this.___RiskAssessmentReviews = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessmentReview>(
                        this,
                        "RiskAssessmentReviews",
                        () => this._RiskAssessmentReviews,
                        e => global::System.Object.Equals(e.RiskAssessmentReview_RiskAssessment, this.Id));
                }
                return this.___RiskAssessmentReviews;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessmentReview> ___RiskAssessmentReviews;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.RiskAssessment.DetailsClass.IImplementation.RiskAssessmentHazards
        {
            get
            {
                return this.RiskAssessmentHazards;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessmentHazard> __RiskAssessmentHazards
        {
            get
            {
                if (this.___RiskAssessmentHazards == null)
                {
                    this.___RiskAssessmentHazards = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessmentHazard>(
                        this,
                        "RiskAssessmentHazards",
                        () => this._RiskAssessmentHazards,
                        e => global::System.Object.Equals(e.RiskAssessmentHazard_RiskAssessment, this.Id));
                }
                return this.___RiskAssessmentHazards;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessmentHazard> ___RiskAssessmentHazards;
        
    }
    #endregion
    
    #region RiskAssessmentStatus
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class RiskAssessmentStatus :
        global::LightSwitchApplication.RiskAssessmentStatus.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.RiskAssessmentStatus.DetailsClass.IImplementation.RiskAssessments
        {
            get
            {
                return this.RiskAssessments;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessment> __RiskAssessments
        {
            get
            {
                if (this.___RiskAssessments == null)
                {
                    this.___RiskAssessments = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessment>(
                        this,
                        "RiskAssessments",
                        () => this._RiskAssessments,
                        e => global::System.Object.Equals(e.RiskAssessmentStatus_RiskAssessment, this.Id));
                }
                return this.___RiskAssessments;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessment> ___RiskAssessments;
        
    }
    #endregion
    
    #region RiskAssessor
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class RiskAssessor :
        global::LightSwitchApplication.RiskAssessor.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
            this.___OnPropertyChanged("Employee");
        }
        
        partial void OnDateTrainedChanged()
        {
            this.___OnPropertyChanged("DateTrained");
        }
        
        partial void OnDateRefresherTrainingDueChanged()
        {
            this.___OnPropertyChanged("DateRefresherTrainingDue");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RiskAssessor.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Employee
        {
            get
            {
                if (this.___Employee == null)
                {
                    this.___Employee = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Employee",
                        new string[] { "Id" },
                        e => global::System.Object.Equals(e.Id, this.Id),
                        () => this._Employee,
                        e => this._Employee = e);
                }
                return this.___Employee;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Employee;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.RiskAssessor.DetailsClass.IImplementation.RiskAssessments_RiskAssessor
        {
            get
            {
                return this.RiskAssessments_RiskAssessor;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessment> __RiskAssessments_RiskAssessor
        {
            get
            {
                if (this.___RiskAssessments_RiskAssessor == null)
                {
                    this.___RiskAssessments_RiskAssessor = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessment>(
                        this,
                        "RiskAssessments_RiskAssessor",
                        () => this._RiskAssessments_RiskAssessor,
                        e => global::System.Object.Equals(e.RiskAssessment_RiskAssessor, this.Id));
                }
                return this.___RiskAssessments_RiskAssessor;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessment> ___RiskAssessments_RiskAssessor;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.RiskAssessor.DetailsClass.IImplementation.RiskAssessments_Approver
        {
            get
            {
                return this.RiskAssessments_Approver;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessment> __RiskAssessments_Approver
        {
            get
            {
                if (this.___RiskAssessments_Approver == null)
                {
                    this.___RiskAssessments_Approver = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessment>(
                        this,
                        "RiskAssessments_Approver",
                        () => this._RiskAssessments_Approver,
                        e => global::System.Object.Equals(e.RiskAssessment_RiskAssessor1, this.Id));
                }
                return this.___RiskAssessments_Approver;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessment> ___RiskAssessments_Approver;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.RiskAssessor.DetailsClass.IImplementation.RiskAssessmentReviews
        {
            get
            {
                return this.RiskAssessmentReviews;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessmentReview> __RiskAssessmentReviews
        {
            get
            {
                if (this.___RiskAssessmentReviews == null)
                {
                    this.___RiskAssessmentReviews = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessmentReview>(
                        this,
                        "RiskAssessmentReviews",
                        () => this._RiskAssessmentReviews,
                        e => global::System.Object.Equals(e.RiskAssessmentReview_RiskAssessor, this.Id));
                }
                return this.___RiskAssessmentReviews;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessmentReview> ___RiskAssessmentReviews;
        
    }
    #endregion
    
    #region RiskType
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class RiskType :
        global::LightSwitchApplication.RiskType.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnTypeOfRiskChanged()
        {
            this.___OnPropertyChanged("TypeOfRisk");
        }
        
        partial void OnInUseChanged()
        {
            this.___OnPropertyChanged("InUse");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.RiskType.DetailsClass.IImplementation.RiskAssessments
        {
            get
            {
                return this.RiskAssessments;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessment> __RiskAssessments
        {
            get
            {
                if (this.___RiskAssessments == null)
                {
                    this.___RiskAssessments = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessment>(
                        this,
                        "RiskAssessments",
                        () => this._RiskAssessments,
                        e => global::System.Object.Equals(e.RiskType_RiskAssessment, this.Id));
                }
                return this.___RiskAssessments;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RiskAssessment> ___RiskAssessments;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.HazardType))
            {
                return new global::LightSwitchApplication.Implementation.HazardType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.RiskAssessmentHazard))
            {
                return new global::LightSwitchApplication.Implementation.RiskAssessmentHazard();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.RiskAssessmentReview))
            {
                return new global::LightSwitchApplication.Implementation.RiskAssessmentReview();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.RiskAssessment))
            {
                return new global::LightSwitchApplication.Implementation.RiskAssessment();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.RiskAssessmentStatus))
            {
                return new global::LightSwitchApplication.Implementation.RiskAssessmentStatus();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.RiskAssessor))
            {
                return new global::LightSwitchApplication.Implementation.RiskAssessor();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.RiskType))
            {
                return new global::LightSwitchApplication.Implementation.RiskType();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            if (typeof(global::LightSwitchApplication.HazardType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.HazardType);
            }
            if (typeof(global::LightSwitchApplication.RiskAssessmentHazard) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.RiskAssessmentHazard);
            }
            if (typeof(global::LightSwitchApplication.RiskAssessmentReview) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.RiskAssessmentReview);
            }
            if (typeof(global::LightSwitchApplication.RiskAssessment) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.RiskAssessment);
            }
            if (typeof(global::LightSwitchApplication.RiskAssessmentStatus) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.RiskAssessmentStatus);
            }
            if (typeof(global::LightSwitchApplication.RiskAssessor) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.RiskAssessor);
            }
            if (typeof(global::LightSwitchApplication.RiskType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.RiskType);
            }
            return null;
        }
    }
}
