

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class RiskAssessmentHazard : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the RiskAssessmentHazard entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public RiskAssessmentHazard()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public RiskAssessmentHazard(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.RiskAssessmentHazard> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RiskAssessmentHazard_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RiskAssessmentHazard_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.SetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string HazardDescription
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.HazardDescription);
            }
            set
            {
                global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.SetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.HazardDescription, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HazardDescription_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HazardDescription_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HazardDescription_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string HazardConsequence
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.HazardConsequence);
            }
            set
            {
                global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.SetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.HazardConsequence, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HazardConsequence_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HazardConsequence_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HazardConsequence_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ControlMeasures
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.ControlMeasures);
            }
            set
            {
                global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.SetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.ControlMeasures, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ControlMeasures_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ControlMeasures_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ControlMeasures_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.SetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.HazardType HazardType
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.HazardType);
            }
            set
            {
                global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.SetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.HazardType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HazardType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HazardType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HazardType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.RiskAssessment RiskAssessment
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.RiskAssessment);
            }
            set
            {
                global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.SetValue(this, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.RiskAssessment, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RiskAssessment_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RiskAssessment_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RiskAssessment_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.RiskAssessmentHazard,
                global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass,
                global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.IImplementation,
                global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass>.Entry
                __RiskAssessmentHazardEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass>.Entry(
                    global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.__RiskAssessmentHazard_CreateNew,
                    global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.__RiskAssessmentHazard_Created,
                    global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.__RiskAssessmentHazard_AllowSaveWithErrors);
            private static global::LightSwitchApplication.RiskAssessmentHazard __RiskAssessmentHazard_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.RiskAssessmentHazard> es)
            {
                return new global::LightSwitchApplication.RiskAssessmentHazard(es);
            }
            private static void __RiskAssessmentHazard_Created(global::LightSwitchApplication.RiskAssessmentHazard e)
            {
                e.RiskAssessmentHazard_Created();
            }
            private static bool __RiskAssessmentHazard_AllowSaveWithErrors(global::LightSwitchApplication.RiskAssessmentHazard e)
            {
                bool result = false;
                e.RiskAssessmentHazard_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string> HazardDescription
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.HazardDescription) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string> HazardConsequence
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.HazardConsequence) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string> ControlMeasures
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.ControlMeasures) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::LightSwitchApplication.HazardType> HazardType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.HazardType) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::LightSwitchApplication.HazardType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::LightSwitchApplication.RiskAssessment> RiskAssessment
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.RiskAssessment) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::LightSwitchApplication.RiskAssessment>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string HazardDescription { get; set; }
                new string HazardConsequence { get; set; }
                new string ControlMeasures { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation HazardType { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation RiskAssessment { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, int>.Data> c, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.RiskAssessmentHazard e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Entry
                    HazardDescription = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Entry(
                        "HazardDescription",
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardDescription_Stub,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardDescription_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardDescription_Validate,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardDescription_GetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardDescription_SetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardDescription_OnValueChanged);
                private static void _HazardDescription_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Data> c, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, object sf)
                {
                    c(d, ref d._HazardDescription, sf);
                }
                private static bool _HazardDescription_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    bool result = false;
                    e.HazardDescription_IsReadOnly(ref result);
                    return result;
                }
                private static void _HazardDescription_Validate(global::LightSwitchApplication.RiskAssessmentHazard e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.HazardDescription_Validate(r);
                }
                private static string _HazardDescription_GetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    return d.ImplementationEntity.HazardDescription;
                }
                private static void _HazardDescription_SetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, string v)
                {
                    d.ImplementationEntity.HazardDescription = v;
                }
                private static void _HazardDescription_OnValueChanged(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    e.HazardDescription_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Entry
                    HazardConsequence = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Entry(
                        "HazardConsequence",
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardConsequence_Stub,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardConsequence_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardConsequence_Validate,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardConsequence_GetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardConsequence_SetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardConsequence_OnValueChanged);
                private static void _HazardConsequence_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Data> c, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, object sf)
                {
                    c(d, ref d._HazardConsequence, sf);
                }
                private static bool _HazardConsequence_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    bool result = false;
                    e.HazardConsequence_IsReadOnly(ref result);
                    return result;
                }
                private static void _HazardConsequence_Validate(global::LightSwitchApplication.RiskAssessmentHazard e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.HazardConsequence_Validate(r);
                }
                private static string _HazardConsequence_GetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    return d.ImplementationEntity.HazardConsequence;
                }
                private static void _HazardConsequence_SetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, string v)
                {
                    d.ImplementationEntity.HazardConsequence = v;
                }
                private static void _HazardConsequence_OnValueChanged(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    e.HazardConsequence_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Entry
                    ControlMeasures = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Entry(
                        "ControlMeasures",
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._ControlMeasures_Stub,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._ControlMeasures_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._ControlMeasures_Validate,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._ControlMeasures_GetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._ControlMeasures_SetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._ControlMeasures_OnValueChanged);
                private static void _ControlMeasures_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Data> c, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, object sf)
                {
                    c(d, ref d._ControlMeasures, sf);
                }
                private static bool _ControlMeasures_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    bool result = false;
                    e.ControlMeasures_IsReadOnly(ref result);
                    return result;
                }
                private static void _ControlMeasures_Validate(global::LightSwitchApplication.RiskAssessmentHazard e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ControlMeasures_Validate(r);
                }
                private static string _ControlMeasures_GetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    return d.ImplementationEntity.ControlMeasures;
                }
                private static void _ControlMeasures_SetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ControlMeasures = v;
                }
                private static void _ControlMeasures_OnValueChanged(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    e.ControlMeasures_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Data> c, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.RiskAssessmentHazard e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.RiskAssessmentHazard e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Data> c, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.RiskAssessmentHazard e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.RiskAssessmentHazard e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.RiskAssessmentHazard e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::LightSwitchApplication.HazardType>.Entry
                    HazardType = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::LightSwitchApplication.HazardType>.Entry(
                        "HazardType",
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardType_Stub,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardType_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardType_Validate,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardType_GetCoreImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardType_GetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardType_SetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardType_Refresh,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._HazardType_OnValueChanged);
                private static void _HazardType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::LightSwitchApplication.HazardType>.Data> c, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, object sf)
                {
                    c(d, ref d._HazardType, sf);
                }
                private static bool _HazardType_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    bool result = false;
                    e.HazardType_IsReadOnly(ref result);
                    return result;
                }
                private static void _HazardType_Validate(global::LightSwitchApplication.RiskAssessmentHazard e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.HazardType_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _HazardType_GetCoreImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    return d.ImplementationEntity.HazardType;
                }
                private static global::LightSwitchApplication.HazardType _HazardType_GetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.HazardType, global::LightSwitchApplication.HazardType.DetailsClass>(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.HazardType, ref d._HazardType);
                }
                private static void _HazardType_SetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, global::LightSwitchApplication.HazardType v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.HazardType, ref d._HazardType, (i, ev) => i.HazardType = ev, v);
                }
                private static void _HazardType_Refresh(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.HazardType, ref d._HazardType);
                }
                private static void _HazardType_OnValueChanged(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    e.HazardType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::LightSwitchApplication.RiskAssessment>.Entry
                    RiskAssessment = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::LightSwitchApplication.RiskAssessment>.Entry(
                        "RiskAssessment",
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RiskAssessment_Stub,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RiskAssessment_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RiskAssessment_Validate,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RiskAssessment_GetCoreImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RiskAssessment_GetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RiskAssessment_SetImplementationValue,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RiskAssessment_Refresh,
                        global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties._RiskAssessment_OnValueChanged);
                private static void _RiskAssessment_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::LightSwitchApplication.RiskAssessment>.Data> c, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, object sf)
                {
                    c(d, ref d._RiskAssessment, sf);
                }
                private static bool _RiskAssessment_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    bool result = false;
                    e.RiskAssessment_IsReadOnly(ref result);
                    return result;
                }
                private static void _RiskAssessment_Validate(global::LightSwitchApplication.RiskAssessmentHazard e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RiskAssessment_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _RiskAssessment_GetCoreImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    return d.ImplementationEntity.RiskAssessment;
                }
                private static global::LightSwitchApplication.RiskAssessment _RiskAssessment_GetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.RiskAssessment, global::LightSwitchApplication.RiskAssessment.DetailsClass>(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.RiskAssessment, ref d._RiskAssessment);
                }
                private static void _RiskAssessment_SetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d, global::LightSwitchApplication.RiskAssessment v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.RiskAssessment, ref d._RiskAssessment, (i, ev) => i.RiskAssessment = ev, v);
                }
                private static void _RiskAssessment_Refresh(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass.PropertySetProperties.RiskAssessment, ref d._RiskAssessment);
                }
                private static void _RiskAssessment_OnValueChanged(global::LightSwitchApplication.RiskAssessmentHazard e)
                {
                    e.RiskAssessment_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Data _HazardDescription;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Data _HazardConsequence;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Data _ControlMeasures;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::LightSwitchApplication.HazardType>.Data _HazardType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessmentHazard, global::LightSwitchApplication.RiskAssessmentHazard.DetailsClass, global::LightSwitchApplication.RiskAssessment>.Data _RiskAssessment;
            
        }
    
        #endregion
    }
    
    #endregion
}
