

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class RiskAssessor : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the RiskAssessor entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public RiskAssessor()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public RiskAssessor(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.RiskAssessor> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.RiskAssessor.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RiskAssessor_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RiskAssessor_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.RiskAssessor.DetailsClass.SetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateTrained
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.DateTrained);
            }
            set
            {
                global::LightSwitchApplication.RiskAssessor.DetailsClass.SetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.DateTrained, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateTrained_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateTrained_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateTrained_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateRefresherTrainingDue
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.DateRefresherTrainingDue);
            }
            set
            {
                global::LightSwitchApplication.RiskAssessor.DetailsClass.SetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.DateRefresherTrainingDue, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateRefresherTrainingDue_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateRefresherTrainingDue_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateRefresherTrainingDue_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.RiskAssessor.DetailsClass.SetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Employee Employee
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Employee);
            }
            set
            {
                global::LightSwitchApplication.RiskAssessor.DetailsClass.SetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Employee, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Employee_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Employee_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Employee_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.RiskAssessment> RiskAssessments_RiskAssessor
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RiskAssessments_RiskAssessor);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.RiskAssessment> RiskAssessments_RiskAssessorQuery
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetQuery(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RiskAssessments_RiskAssessor);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.RiskAssessment> RiskAssessments_Approver
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RiskAssessments_Approver);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.RiskAssessment> RiskAssessments_ApproverQuery
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetQuery(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RiskAssessments_Approver);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.RiskAssessmentReview> RiskAssessmentReviews
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetValue(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RiskAssessmentReviews);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.RiskAssessmentReview> RiskAssessmentReviewsQuery
        {
            get
            {
                return global::LightSwitchApplication.RiskAssessor.DetailsClass.GetQuery(this, global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RiskAssessmentReviews);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.RiskAssessor,
                global::LightSwitchApplication.RiskAssessor.DetailsClass,
                global::LightSwitchApplication.RiskAssessor.DetailsClass.IImplementation,
                global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass>.Entry
                __RiskAssessorEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass>.Entry(
                    global::LightSwitchApplication.RiskAssessor.DetailsClass.__RiskAssessor_CreateNew,
                    global::LightSwitchApplication.RiskAssessor.DetailsClass.__RiskAssessor_Created,
                    global::LightSwitchApplication.RiskAssessor.DetailsClass.__RiskAssessor_AllowSaveWithErrors);
            private static global::LightSwitchApplication.RiskAssessor __RiskAssessor_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.RiskAssessor> es)
            {
                return new global::LightSwitchApplication.RiskAssessor(es);
            }
            private static void __RiskAssessor_Created(global::LightSwitchApplication.RiskAssessor e)
            {
                e.RiskAssessor_Created();
            }
            private static bool __RiskAssessor_AllowSaveWithErrors(global::LightSwitchApplication.RiskAssessor e)
            {
                bool result = false;
                e.RiskAssessor_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.DateTime> DateTrained
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.DateTrained) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.DateTime> DateRefresherTrainingDue
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.DateRefresherTrainingDue) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.Employee> Employee
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Employee) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.Employee>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessment> RiskAssessments_RiskAssessor
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RiskAssessments_RiskAssessor) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessment>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessment> RiskAssessments_Approver
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RiskAssessments_Approver) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessment>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessmentReview> RiskAssessmentReviews
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RiskAssessmentReviews) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessmentReview>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new global::System.DateTime DateTrained { get; set; }
                new global::System.DateTime DateRefresherTrainingDue { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Employee { get; set; }
                new global::System.Collections.IEnumerable RiskAssessments_RiskAssessor { get; }
                new global::System.Collections.IEnumerable RiskAssessments_Approver { get; }
                new global::System.Collections.IEnumerable RiskAssessmentReviews { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, int>.Data> c, global::LightSwitchApplication.RiskAssessor.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessor e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.RiskAssessor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.RiskAssessor e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.DateTime>.Entry
                    DateTrained = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.DateTime>.Entry(
                        "DateTrained",
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._DateTrained_Stub,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._DateTrained_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._DateTrained_Validate,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._DateTrained_GetImplementationValue,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._DateTrained_SetImplementationValue,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._DateTrained_OnValueChanged);
                private static void _DateTrained_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.RiskAssessor.DetailsClass d, object sf)
                {
                    c(d, ref d._DateTrained, sf);
                }
                private static bool _DateTrained_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessor e)
                {
                    bool result = false;
                    e.DateTrained_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateTrained_Validate(global::LightSwitchApplication.RiskAssessor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateTrained_Validate(r);
                }
                private static global::System.DateTime _DateTrained_GetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.ImplementationEntity.DateTrained;
                }
                private static void _DateTrained_SetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DateTrained = global::LightSwitchApplication.RiskAssessor.DetailsClass.TruncateDate(v);
                }
                private static void _DateTrained_OnValueChanged(global::LightSwitchApplication.RiskAssessor e)
                {
                    e.DateTrained_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.DateTime>.Entry
                    DateRefresherTrainingDue = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.DateTime>.Entry(
                        "DateRefresherTrainingDue",
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._DateRefresherTrainingDue_Stub,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._DateRefresherTrainingDue_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._DateRefresherTrainingDue_Validate,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._DateRefresherTrainingDue_GetImplementationValue,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._DateRefresherTrainingDue_SetImplementationValue,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._DateRefresherTrainingDue_OnValueChanged);
                private static void _DateRefresherTrainingDue_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.RiskAssessor.DetailsClass d, object sf)
                {
                    c(d, ref d._DateRefresherTrainingDue, sf);
                }
                private static bool _DateRefresherTrainingDue_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessor e)
                {
                    bool result = false;
                    e.DateRefresherTrainingDue_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateRefresherTrainingDue_Validate(global::LightSwitchApplication.RiskAssessor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateRefresherTrainingDue_Validate(r);
                }
                private static global::System.DateTime _DateRefresherTrainingDue_GetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.ImplementationEntity.DateRefresherTrainingDue;
                }
                private static void _DateRefresherTrainingDue_SetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DateRefresherTrainingDue = global::LightSwitchApplication.RiskAssessor.DetailsClass.TruncateDate(v);
                }
                private static void _DateRefresherTrainingDue_OnValueChanged(global::LightSwitchApplication.RiskAssessor e)
                {
                    e.DateRefresherTrainingDue_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, string>.Data> c, global::LightSwitchApplication.RiskAssessor.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessor e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.RiskAssessor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.RiskAssessor e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.RiskAssessor.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessor e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.RiskAssessor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.RiskAssessor e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, string>.Data> c, global::LightSwitchApplication.RiskAssessor.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessor e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.RiskAssessor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.RiskAssessor e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.RiskAssessor.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessor e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.RiskAssessor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.RiskAssessor e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.RiskAssessor.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessor e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.RiskAssessor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.RiskAssessor e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.Employee>.Entry
                    Employee = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.Employee>.Entry(
                        "Employee",
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Employee_Stub,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Employee_ComputeIsReadOnly,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Employee_Validate,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Employee_GetCoreImplementationValue,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Employee_GetImplementationValue,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Employee_SetImplementationValue,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Employee_Refresh,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._Employee_OnValueChanged);
                private static void _Employee_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.Employee>.Data> c, global::LightSwitchApplication.RiskAssessor.DetailsClass d, object sf)
                {
                    c(d, ref d._Employee, sf);
                }
                private static bool _Employee_ComputeIsReadOnly(global::LightSwitchApplication.RiskAssessor e)
                {
                    bool result = false;
                    e.Employee_IsReadOnly(ref result);
                    return result;
                }
                private static void _Employee_Validate(global::LightSwitchApplication.RiskAssessor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Employee_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Employee_GetCoreImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.ImplementationEntity.Employee;
                }
                private static global::LightSwitchApplication.Employee _Employee_GetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Employee, global::LightSwitchApplication.Employee.DetailsClass>(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Employee, ref d._Employee);
                }
                private static void _Employee_SetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass d, global::LightSwitchApplication.Employee v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Employee, ref d._Employee, (i, ev) => i.Employee = ev, v);
                }
                private static void _Employee_Refresh(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.Employee, ref d._Employee);
                }
                private static void _Employee_OnValueChanged(global::LightSwitchApplication.RiskAssessor e)
                {
                    e.Employee_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessment>.Entry
                    RiskAssessments_RiskAssessor = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessment>.Entry(
                        "RiskAssessments_RiskAssessor",
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RiskAssessments_RiskAssessor_Stub,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RiskAssessments_RiskAssessor_GetReferencedEntities,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RiskAssessments_RiskAssessor_GetEntityCollection);
                private static void _RiskAssessments_RiskAssessor_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessment>.Data> c, global::LightSwitchApplication.RiskAssessor.DetailsClass d, object sf)
                {
                    c(d, ref d._RiskAssessments_RiskAssessor, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.RiskAssessment> _RiskAssessments_RiskAssessor_GetReferencedEntities(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.RiskAssessment, global::LightSwitchApplication.RiskAssessment.DetailsClass>(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RiskAssessments_RiskAssessor, ref d._RiskAssessments_RiskAssessor);
                }
                private static global::System.Collections.IEnumerable _RiskAssessments_RiskAssessor_GetEntityCollection(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.ImplementationEntity.RiskAssessments_RiskAssessor;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessment>.Entry
                    RiskAssessments_Approver = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessment>.Entry(
                        "RiskAssessments_Approver",
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RiskAssessments_Approver_Stub,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RiskAssessments_Approver_GetReferencedEntities,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RiskAssessments_Approver_GetEntityCollection);
                private static void _RiskAssessments_Approver_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessment>.Data> c, global::LightSwitchApplication.RiskAssessor.DetailsClass d, object sf)
                {
                    c(d, ref d._RiskAssessments_Approver, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.RiskAssessment> _RiskAssessments_Approver_GetReferencedEntities(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.RiskAssessment, global::LightSwitchApplication.RiskAssessment.DetailsClass>(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RiskAssessments_Approver, ref d._RiskAssessments_Approver);
                }
                private static global::System.Collections.IEnumerable _RiskAssessments_Approver_GetEntityCollection(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.ImplementationEntity.RiskAssessments_Approver;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessmentReview>.Entry
                    RiskAssessmentReviews = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessmentReview>.Entry(
                        "RiskAssessmentReviews",
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RiskAssessmentReviews_Stub,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RiskAssessmentReviews_GetReferencedEntities,
                        global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties._RiskAssessmentReviews_GetEntityCollection);
                private static void _RiskAssessmentReviews_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RiskAssessor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessmentReview>.Data> c, global::LightSwitchApplication.RiskAssessor.DetailsClass d, object sf)
                {
                    c(d, ref d._RiskAssessmentReviews, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.RiskAssessmentReview> _RiskAssessmentReviews_GetReferencedEntities(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.RiskAssessmentReview, global::LightSwitchApplication.RiskAssessmentReview.DetailsClass>(global::LightSwitchApplication.RiskAssessor.DetailsClass.PropertySetProperties.RiskAssessmentReviews, ref d._RiskAssessmentReviews);
                }
                private static global::System.Collections.IEnumerable _RiskAssessmentReviews_GetEntityCollection(global::LightSwitchApplication.RiskAssessor.DetailsClass d)
                {
                    return d.ImplementationEntity.RiskAssessmentReviews;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.DateTime>.Data _DateTrained;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.DateTime>.Data _DateRefresherTrainingDue;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.Employee>.Data _Employee;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessment>.Data _RiskAssessments_RiskAssessor;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessment>.Data _RiskAssessments_Approver;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RiskAssessor, global::LightSwitchApplication.RiskAssessor.DetailsClass, global::LightSwitchApplication.RiskAssessmentReview>.Data _RiskAssessmentReviews;
            
        }
    
        #endregion
    }
    
    #endregion
}
